"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function LoginPage() {
  const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
      const [error, setError] = useState("");
        const [loading, setLoading] = useState(false);
          const router = useRouter();
            const supabase = createClient();

              async function handleLogin(e: React.FormEvent) {
                  e.preventDefault();
                      setLoading(true);
                          setError("");

                              const { error } = await supabase.auth.signInWithPassword({ email, password });

                                  if (error) {
                                        setError(error.message);
                                              setLoading(false);
                                                  } else {
                                                        router.push("/dashboard");
                                                            }
                                                              }

                                                                return (
                                                                    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--paper)" }}>
                                                                          <div style={{ width: "100%", maxWidth: "400px", padding: "2rem", background: "white", borderRadius: "12px", boxShadow: "0 4px 24px rgba(0,0,0,0.08)" }}>
                                                                                  <div style={{ marginBottom: "2rem", textAlign: "center" }}>
                                                                                            <h1 style={{ fontSize: "1.75rem", fontWeight: "700", color: "var(--ink)" }}>Jobulary 360</h1>
                                                                                                      <p style={{ color: "#666", marginTop: "0.5rem" }}>Sign in to your account</p>
                                                                                                              </div>

                                                                                                                      <form onSubmit={handleLogin}>
                                                                                                                                <div style={{ marginBottom: "1rem" }}>
                                                                                                                                            <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "500" }}>Email</label>
                                                                                                                                                        <input
                                                                                                                                                                      type="email"
                                                                                                                                                                                    value={email}
                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                required
                                                                                                                                                                                                                              style={{ width: "100%", padding: "0.75rem", border: "1px solid #ddd", borderRadius: "8px", fontSize: "1rem" }}
                                                                                                                                                                                                                                            placeholder="you@company.com"
                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                            <div style={{ marginBottom: "1.5rem" }}>
                                                                                                                                                                                                                                                                                        <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "500" }}>Password</label>
                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                          style={{ width: "100%", padding: "0.75rem", border: "1px solid #ddd", borderRadius: "8px", fontSize: "1rem" }}
                                                                                                                                                                                                                                                                                                                                                                                        placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                        {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ padding: "0.75rem", background: "#fef2f2", border: "1px solid #fecaca", borderRadius: "8px", color: "#dc2626", marginBottom: "1rem", fontSize: "0.875rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: "100%", padding: "0.875rem", background: "var(--teal)", color: "white", border: "none", borderRadius: "8px", fontSize: "1rem", fontWeight: "600", opacity: loading ? 0.7 : 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? "Signing in..." : "Sign In"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ textAlign: "center", marginTop: "1.5rem", color: "#666", fontSize: "0.875rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Don&apos;t have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/auth/signup" style={{ color: "var(--teal)", fontWeight: "500" }}>Sign up</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }